modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="MIT"

[[mods]]
modId="pickup" #mandatory
version="${mod_version}" #mandatory
displayName="Pickup" #mandatory
#logoFile="pickup.png"
authors="Chemiofitor"
description=''' '''
logoFile="pickup.png"

[[dependencies.pickup]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.pickup]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="BOTH"
